// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGe6kVC3r64po7_MPf9V_JjuegNk5NkZQ',
    appId: '1:827383470989:web:9505be0fb4305458467bc4',
    messagingSenderId: '827383470989',
    projectId: 'habit-tracke',
    authDomain: 'habit-tracke.firebaseapp.com',
    storageBucket: 'habit-tracke.firebasestorage.app',
    measurementId: 'G-NPKNN8V7SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0CGePGGhP3RIBK4Jr2bn-7U5wlCSy3qs',
    appId: '1:827383470989:android:3268ce39e0ba6222467bc4',
    messagingSenderId: '827383470989',
    projectId: 'habit-tracke',
    storageBucket: 'habit-tracke.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYuC5faRZS2X0XY-rc7AR72SiiwT3I5sc',
    appId: '1:827383470989:ios:8200ec1f53b1039e467bc4',
    messagingSenderId: '827383470989',
    projectId: 'habit-tracke',
    storageBucket: 'habit-tracke.firebasestorage.app',
    androidClientId: '827383470989-gft2nhdmj7vja63idc0idps4lmtdd0fb.apps.googleusercontent.com',
    iosClientId: '827383470989-epdc5puskn3g2c3tt9engp63tsajrliu.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYuC5faRZS2X0XY-rc7AR72SiiwT3I5sc',
    appId: '1:827383470989:ios:8200ec1f53b1039e467bc4',
    messagingSenderId: '827383470989',
    projectId: 'habit-tracke',
    storageBucket: 'habit-tracke.firebasestorage.app',
    androidClientId: '827383470989-gft2nhdmj7vja63idc0idps4lmtdd0fb.apps.googleusercontent.com',
    iosClientId: '827383470989-epdc5puskn3g2c3tt9engp63tsajrliu.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGe6kVC3r64po7_MPf9V_JjuegNk5NkZQ',
    appId: '1:827383470989:web:c51eada134a0fae2467bc4',
    messagingSenderId: '827383470989',
    projectId: 'habit-tracke',
    authDomain: 'habit-tracke.firebaseapp.com',
    storageBucket: 'habit-tracke.firebasestorage.app',
    measurementId: 'G-0T4BT7QTX8',
  );
}
